# TCL File Generated by Component Editor 20.1
# Sun May 25 01:25:10 BST 2025
# DO NOT MODIFY


# 
# Adaptive_FLL "AFLL" v1.0
# Cameron Wade 2025.05.25.01:25:10
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module Adaptive_FLL
# 
set_module_property DESCRIPTION ""
set_module_property NAME Adaptive_FLL
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Cameron Wade"
set_module_property DISPLAY_NAME AFLL
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL afll
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file afll.v VERILOG PATH afll/afll.v TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter THRESHOLD STD_LOGIC_VECTOR 5000
set_parameter_property THRESHOLD DEFAULT_VALUE 5000
set_parameter_property THRESHOLD DISPLAY_NAME THRESHOLD
set_parameter_property THRESHOLD WIDTH 34
set_parameter_property THRESHOLD TYPE STD_LOGIC_VECTOR
set_parameter_property THRESHOLD UNITS None
set_parameter_property THRESHOLD ALLOWED_RANGES 0:17179869183
set_parameter_property THRESHOLD HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 100000000
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point scan_dir
# 
add_interface scan_dir conduit end
set_interface_property scan_dir associatedClock clock
set_interface_property scan_dir associatedReset ""
set_interface_property scan_dir ENABLED true
set_interface_property scan_dir EXPORT_OF ""
set_interface_property scan_dir PORT_NAME_MAP ""
set_interface_property scan_dir CMSIS_SVD_VARIABLES ""
set_interface_property scan_dir SVD_ADDRESS_GROUP ""

add_interface_port scan_dir scan_dir export Input 1


# 
# connection point sync_start
# 
add_interface sync_start conduit end
set_interface_property sync_start associatedClock clock
set_interface_property sync_start associatedReset ""
set_interface_property sync_start ENABLED true
set_interface_property sync_start EXPORT_OF ""
set_interface_property sync_start PORT_NAME_MAP ""
set_interface_property sync_start CMSIS_SVD_VARIABLES ""
set_interface_property sync_start SVD_ADDRESS_GROUP ""

add_interface_port sync_start sync_start export Input 1


# 
# connection point t_ltr
# 
add_interface t_ltr conduit end
set_interface_property t_ltr associatedClock clock
set_interface_property t_ltr associatedReset ""
set_interface_property t_ltr ENABLED true
set_interface_property t_ltr EXPORT_OF ""
set_interface_property t_ltr PORT_NAME_MAP ""
set_interface_property t_ltr CMSIS_SVD_VARIABLES ""
set_interface_property t_ltr SVD_ADDRESS_GROUP ""

add_interface_port t_ltr t_ltr export Output 32


# 
# connection point t_rtl
# 
add_interface t_rtl conduit end
set_interface_property t_rtl associatedClock clock
set_interface_property t_rtl associatedReset ""
set_interface_property t_rtl ENABLED true
set_interface_property t_rtl EXPORT_OF ""
set_interface_property t_rtl PORT_NAME_MAP ""
set_interface_property t_rtl CMSIS_SVD_VARIABLES ""
set_interface_property t_rtl SVD_ADDRESS_GROUP ""

add_interface_port t_rtl t_rtl export Output 32

