# TCL File Generated by Component Editor 20.1
# Sun May 25 03:12:21 BST 2025
# DO NOT MODIFY


# 
# demux_to_stereo_buffer "demux_to_stereo_buffer" v1.0
# Cameron Wade 2025.05.25.03:12:21
# Splits scan to Left and Right and buffers
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module demux_to_stereo_buffer
# 
set_module_property DESCRIPTION "Splits scan to Left and Right and buffers"
set_module_property NAME demux_to_stereo_buffer
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Cameron Wade"
set_module_property DISPLAY_NAME demux_to_stereo_buffer
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL demux_to_stereo_buffer
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file demux_to_stereo_buffer.v VERILOG PATH demux_to_stereo_buffer/demux_to_stereo_buffer.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 100000000
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point sample_in
# 
add_interface sample_in conduit end
set_interface_property sample_in associatedClock clock
set_interface_property sample_in associatedReset ""
set_interface_property sample_in ENABLED true
set_interface_property sample_in EXPORT_OF ""
set_interface_property sample_in PORT_NAME_MAP ""
set_interface_property sample_in CMSIS_SVD_VARIABLES ""
set_interface_property sample_in SVD_ADDRESS_GROUP ""

add_interface_port sample_in sample_in export Input 16


# 
# connection point valid_in
# 
add_interface valid_in conduit end
set_interface_property valid_in associatedClock clock
set_interface_property valid_in associatedReset ""
set_interface_property valid_in ENABLED true
set_interface_property valid_in EXPORT_OF ""
set_interface_property valid_in PORT_NAME_MAP ""
set_interface_property valid_in CMSIS_SVD_VARIABLES ""
set_interface_property valid_in SVD_ADDRESS_GROUP ""

add_interface_port valid_in valid_in export Input 1


# 
# connection point left_sample
# 
add_interface left_sample conduit end
set_interface_property left_sample associatedClock clock
set_interface_property left_sample associatedReset ""
set_interface_property left_sample ENABLED true
set_interface_property left_sample EXPORT_OF ""
set_interface_property left_sample PORT_NAME_MAP ""
set_interface_property left_sample CMSIS_SVD_VARIABLES ""
set_interface_property left_sample SVD_ADDRESS_GROUP ""

add_interface_port left_sample left_sample export Output 16


# 
# connection point sample_pair_valid
# 
add_interface sample_pair_valid conduit end
set_interface_property sample_pair_valid associatedClock clock
set_interface_property sample_pair_valid associatedReset ""
set_interface_property sample_pair_valid ENABLED true
set_interface_property sample_pair_valid EXPORT_OF ""
set_interface_property sample_pair_valid PORT_NAME_MAP ""
set_interface_property sample_pair_valid CMSIS_SVD_VARIABLES ""
set_interface_property sample_pair_valid SVD_ADDRESS_GROUP ""

add_interface_port sample_pair_valid sample_pair_valid export Output 1


# 
# connection point right_sample
# 
add_interface right_sample conduit end
set_interface_property right_sample associatedClock clock
set_interface_property right_sample associatedReset ""
set_interface_property right_sample ENABLED true
set_interface_property right_sample EXPORT_OF ""
set_interface_property right_sample PORT_NAME_MAP ""
set_interface_property right_sample CMSIS_SVD_VARIABLES ""
set_interface_property right_sample SVD_ADDRESS_GROUP ""

add_interface_port right_sample right_sample export Output 16


# 
# connection point dir
# 
add_interface dir conduit end
set_interface_property dir associatedClock clock
set_interface_property dir associatedReset ""
set_interface_property dir ENABLED true
set_interface_property dir EXPORT_OF ""
set_interface_property dir PORT_NAME_MAP ""
set_interface_property dir CMSIS_SVD_VARIABLES ""
set_interface_property dir SVD_ADDRESS_GROUP ""

add_interface_port dir dir export Input 1

