# TCL File Generated by Component Editor 20.1
# Sun May 25 03:38:05 BST 2025
# DO NOT MODIFY


# 
# scan_cycle_controller "scan_cycle_controller" v1.0
# Cameron Wade 2025.05.25.03:38:05
# Manages both channel scan controls
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module scan_cycle_controller
# 
set_module_property DESCRIPTION "Manages both channel scan controls"
set_module_property NAME scan_cycle_controller
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Cameron Wade"
set_module_property DISPLAY_NAME scan_cycle_controller
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL scan_cycle_controller
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file scan_cycle_controller.v VERILOG PATH scan_cycle_controller/scan_cycle_controller.v TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter IDLE STD_LOGIC_VECTOR 0
set_parameter_property IDLE DEFAULT_VALUE 0
set_parameter_property IDLE DISPLAY_NAME IDLE
set_parameter_property IDLE TYPE STD_LOGIC_VECTOR
set_parameter_property IDLE UNITS None
set_parameter_property IDLE ALLOWED_RANGES 0:7
set_parameter_property IDLE HDL_PARAMETER true
add_parameter WAIT_L STD_LOGIC_VECTOR 1
set_parameter_property WAIT_L DEFAULT_VALUE 1
set_parameter_property WAIT_L DISPLAY_NAME WAIT_L
set_parameter_property WAIT_L TYPE STD_LOGIC_VECTOR
set_parameter_property WAIT_L UNITS None
set_parameter_property WAIT_L ALLOWED_RANGES 0:7
set_parameter_property WAIT_L HDL_PARAMETER true
add_parameter WAIT_R STD_LOGIC_VECTOR 2
set_parameter_property WAIT_R DEFAULT_VALUE 2
set_parameter_property WAIT_R DISPLAY_NAME WAIT_R
set_parameter_property WAIT_R TYPE STD_LOGIC_VECTOR
set_parameter_property WAIT_R UNITS None
set_parameter_property WAIT_R ALLOWED_RANGES 0:7
set_parameter_property WAIT_R HDL_PARAMETER true
add_parameter COMPLETE STD_LOGIC_VECTOR 3
set_parameter_property COMPLETE DEFAULT_VALUE 3
set_parameter_property COMPLETE DISPLAY_NAME COMPLETE
set_parameter_property COMPLETE TYPE STD_LOGIC_VECTOR
set_parameter_property COMPLETE UNITS None
set_parameter_property COMPLETE ALLOWED_RANGES 0:7
set_parameter_property COMPLETE HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 100000000
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point dir
# 
add_interface dir conduit end
set_interface_property dir associatedClock clock
set_interface_property dir associatedReset ""
set_interface_property dir ENABLED true
set_interface_property dir EXPORT_OF ""
set_interface_property dir PORT_NAME_MAP ""
set_interface_property dir CMSIS_SVD_VARIABLES ""
set_interface_property dir SVD_ADDRESS_GROUP ""

add_interface_port dir dir export Output 1


# 
# connection point sig_l_detected
# 
add_interface sig_l_detected conduit end
set_interface_property sig_l_detected associatedClock clock
set_interface_property sig_l_detected associatedReset ""
set_interface_property sig_l_detected ENABLED true
set_interface_property sig_l_detected EXPORT_OF ""
set_interface_property sig_l_detected PORT_NAME_MAP ""
set_interface_property sig_l_detected CMSIS_SVD_VARIABLES ""
set_interface_property sig_l_detected SVD_ADDRESS_GROUP ""

add_interface_port sig_l_detected sig_l_detected export Input 1


# 
# connection point sig_l_enable
# 
add_interface sig_l_enable conduit end
set_interface_property sig_l_enable associatedClock clock
set_interface_property sig_l_enable associatedReset ""
set_interface_property sig_l_enable ENABLED true
set_interface_property sig_l_enable EXPORT_OF ""
set_interface_property sig_l_enable PORT_NAME_MAP ""
set_interface_property sig_l_enable CMSIS_SVD_VARIABLES ""
set_interface_property sig_l_enable SVD_ADDRESS_GROUP ""

add_interface_port sig_l_enable sig_l_enable export Output 1


# 
# connection point sig_r_detected
# 
add_interface sig_r_detected conduit end
set_interface_property sig_r_detected associatedClock clock
set_interface_property sig_r_detected associatedReset ""
set_interface_property sig_r_detected ENABLED true
set_interface_property sig_r_detected EXPORT_OF ""
set_interface_property sig_r_detected PORT_NAME_MAP ""
set_interface_property sig_r_detected CMSIS_SVD_VARIABLES ""
set_interface_property sig_r_detected SVD_ADDRESS_GROUP ""

add_interface_port sig_r_detected sig_r_detected export Input 1


# 
# connection point sig_r_enable
# 
add_interface sig_r_enable conduit end
set_interface_property sig_r_enable associatedClock clock
set_interface_property sig_r_enable associatedReset ""
set_interface_property sig_r_enable ENABLED true
set_interface_property sig_r_enable EXPORT_OF ""
set_interface_property sig_r_enable PORT_NAME_MAP ""
set_interface_property sig_r_enable CMSIS_SVD_VARIABLES ""
set_interface_property sig_r_enable SVD_ADDRESS_GROUP ""

add_interface_port sig_r_enable sig_r_enable export Output 1


# 
# connection point sync_start
# 
add_interface sync_start conduit end
set_interface_property sync_start associatedClock clock
set_interface_property sync_start associatedReset ""
set_interface_property sync_start ENABLED true
set_interface_property sync_start EXPORT_OF ""
set_interface_property sync_start PORT_NAME_MAP ""
set_interface_property sync_start CMSIS_SVD_VARIABLES ""
set_interface_property sync_start SVD_ADDRESS_GROUP ""

add_interface_port sync_start sync_start export Input 1

