# TCL File Generated by Component Editor 20.1
# Sun May 25 02:08:17 BST 2025
# DO NOT MODIFY


# 
# sync_distro "sync_distro" v1.0
# Cameron Wade 2025.05.25.02:08:17
# To connect 3 conduits together
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module sync_distro
# 
set_module_property DESCRIPTION "To connect 3 conduits together"
set_module_property NAME sync_distro
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Cameron Wade"
set_module_property DISPLAY_NAME sync_distro
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL sync_distributor
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file sync_distro.v VERILOG PATH sync_distro/sync_distro.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point sync_to_afll
# 
add_interface sync_to_afll conduit end
set_interface_property sync_to_afll associatedClock ""
set_interface_property sync_to_afll associatedReset ""
set_interface_property sync_to_afll ENABLED true
set_interface_property sync_to_afll EXPORT_OF ""
set_interface_property sync_to_afll PORT_NAME_MAP ""
set_interface_property sync_to_afll CMSIS_SVD_VARIABLES ""
set_interface_property sync_to_afll SVD_ADDRESS_GROUP ""

add_interface_port sync_to_afll sync_to_afll export Output 1


# 
# connection point sync_to_sig_timestamp
# 
add_interface sync_to_sig_timestamp conduit end
set_interface_property sync_to_sig_timestamp associatedClock ""
set_interface_property sync_to_sig_timestamp associatedReset ""
set_interface_property sync_to_sig_timestamp ENABLED true
set_interface_property sync_to_sig_timestamp EXPORT_OF ""
set_interface_property sync_to_sig_timestamp PORT_NAME_MAP ""
set_interface_property sync_to_sig_timestamp CMSIS_SVD_VARIABLES ""
set_interface_property sync_to_sig_timestamp SVD_ADDRESS_GROUP ""

add_interface_port sync_to_sig_timestamp sync_to_sig_timestamp export Output 1


# 
# connection point sync_in
# 
add_interface sync_in conduit end
set_interface_property sync_in associatedClock ""
set_interface_property sync_in associatedReset ""
set_interface_property sync_in ENABLED true
set_interface_property sync_in EXPORT_OF ""
set_interface_property sync_in PORT_NAME_MAP ""
set_interface_property sync_in CMSIS_SVD_VARIABLES ""
set_interface_property sync_in SVD_ADDRESS_GROUP ""

add_interface_port sync_in sync_in export Input 1


# 
# connection point sync_to_scan_dir_1
# 
add_interface sync_to_scan_dir_1 conduit end
set_interface_property sync_to_scan_dir_1 associatedClock ""
set_interface_property sync_to_scan_dir_1 associatedReset ""
set_interface_property sync_to_scan_dir_1 ENABLED true
set_interface_property sync_to_scan_dir_1 EXPORT_OF ""
set_interface_property sync_to_scan_dir_1 PORT_NAME_MAP ""
set_interface_property sync_to_scan_dir_1 CMSIS_SVD_VARIABLES ""
set_interface_property sync_to_scan_dir_1 SVD_ADDRESS_GROUP ""

add_interface_port sync_to_scan_dir_1 sync_to_scan_dir export Output 1

