# TCL File Generated by Component Editor 20.1
# Tue May 27 02:26:36 BST 2025
# DO NOT MODIFY


# 
# i2s_tx "i2s_tx" v1.0
# Cameron Wade 2025.05.27.02:26:36
# i2s transmitter, for 100M clk, generates 3.125MHz clk
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module i2s_tx
# 
set_module_property DESCRIPTION "i2s transmitter, for 100M clk, generates 3.125MHz clk"
set_module_property NAME i2s_tx
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Cameron Wade"
set_module_property DISPLAY_NAME i2s_tx
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL i2s_transmitter
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file i2s_tx_wclk.v VERILOG PATH i2s_tx/i2s_tx_wclk.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 100000000
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point valid_in
# 
add_interface valid_in conduit end
set_interface_property valid_in associatedClock clock
set_interface_property valid_in associatedReset ""
set_interface_property valid_in ENABLED true
set_interface_property valid_in EXPORT_OF ""
set_interface_property valid_in PORT_NAME_MAP ""
set_interface_property valid_in CMSIS_SVD_VARIABLES ""
set_interface_property valid_in SVD_ADDRESS_GROUP ""

add_interface_port valid_in valid_in export Input 1


# 
# connection point sdata
# 
add_interface sdata conduit end
set_interface_property sdata associatedClock clock
set_interface_property sdata associatedReset ""
set_interface_property sdata ENABLED true
set_interface_property sdata EXPORT_OF ""
set_interface_property sdata PORT_NAME_MAP ""
set_interface_property sdata CMSIS_SVD_VARIABLES ""
set_interface_property sdata SVD_ADDRESS_GROUP ""

add_interface_port sdata sdata export Output 1


# 
# connection point sample_L
# 
add_interface sample_L conduit end
set_interface_property sample_L associatedClock clock
set_interface_property sample_L associatedReset ""
set_interface_property sample_L ENABLED true
set_interface_property sample_L EXPORT_OF ""
set_interface_property sample_L PORT_NAME_MAP ""
set_interface_property sample_L CMSIS_SVD_VARIABLES ""
set_interface_property sample_L SVD_ADDRESS_GROUP ""

add_interface_port sample_L sample_L export Input 16


# 
# connection point sample_R
# 
add_interface sample_R conduit end
set_interface_property sample_R associatedClock clock
set_interface_property sample_R associatedReset ""
set_interface_property sample_R ENABLED true
set_interface_property sample_R EXPORT_OF ""
set_interface_property sample_R PORT_NAME_MAP ""
set_interface_property sample_R CMSIS_SVD_VARIABLES ""
set_interface_property sample_R SVD_ADDRESS_GROUP ""

add_interface_port sample_R sample_R export Input 16


# 
# connection point lrclk
# 
add_interface lrclk conduit end
set_interface_property lrclk associatedClock clock
set_interface_property lrclk associatedReset ""
set_interface_property lrclk ENABLED true
set_interface_property lrclk EXPORT_OF ""
set_interface_property lrclk PORT_NAME_MAP ""
set_interface_property lrclk CMSIS_SVD_VARIABLES ""
set_interface_property lrclk SVD_ADDRESS_GROUP ""

add_interface_port lrclk lrclk export Output 1


# 
# connection point bclk
# 
add_interface bclk conduit end
set_interface_property bclk associatedClock clock
set_interface_property bclk associatedReset ""
set_interface_property bclk ENABLED true
set_interface_property bclk EXPORT_OF ""
set_interface_property bclk PORT_NAME_MAP ""
set_interface_property bclk CMSIS_SVD_VARIABLES ""
set_interface_property bclk SVD_ADDRESS_GROUP ""

add_interface_port bclk bclk export Output 1

