# TCL File Generated by Component Editor 20.1
# Thu Jun 05 14:03:27 BST 2025
# DO NOT MODIFY


# 
# pid_focus_controller "pid_focus_controller" v1.0
# Cameron Wade 2025.06.05.14:03:27
# pid and PWM generation, set threshold over SPI
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module pid_focus_controller
# 
set_module_property DESCRIPTION "pid and PWM generation, set threshold over SPI"
set_module_property NAME pid_focus_controller
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Cameron Wade"
set_module_property DISPLAY_NAME pid_focus_controller
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL pid_focus_controller
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file pid_focus_controller.v VERILOG PATH 6PidFocus/pid_focus_controller.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 100000000
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point focus_signal
# 
add_interface focus_signal conduit end
set_interface_property focus_signal associatedClock clock
set_interface_property focus_signal associatedReset ""
set_interface_property focus_signal ENABLED true
set_interface_property focus_signal EXPORT_OF ""
set_interface_property focus_signal PORT_NAME_MAP ""
set_interface_property focus_signal CMSIS_SVD_VARIABLES ""
set_interface_property focus_signal SVD_ADDRESS_GROUP ""

add_interface_port focus_signal focus_signal export Input 16


# 
# connection point kp
# 
add_interface kp conduit end
set_interface_property kp associatedClock clock
set_interface_property kp associatedReset ""
set_interface_property kp ENABLED true
set_interface_property kp EXPORT_OF ""
set_interface_property kp PORT_NAME_MAP ""
set_interface_property kp CMSIS_SVD_VARIABLES ""
set_interface_property kp SVD_ADDRESS_GROUP ""

add_interface_port kp kp export Input 16


# 
# connection point ki
# 
add_interface ki conduit end
set_interface_property ki associatedClock clock
set_interface_property ki associatedReset ""
set_interface_property ki ENABLED true
set_interface_property ki EXPORT_OF ""
set_interface_property ki PORT_NAME_MAP ""
set_interface_property ki CMSIS_SVD_VARIABLES ""
set_interface_property ki SVD_ADDRESS_GROUP ""

add_interface_port ki ki export Input 16


# 
# connection point kd
# 
add_interface kd conduit end
set_interface_property kd associatedClock clock
set_interface_property kd associatedReset ""
set_interface_property kd ENABLED true
set_interface_property kd EXPORT_OF ""
set_interface_property kd PORT_NAME_MAP ""
set_interface_property kd CMSIS_SVD_VARIABLES ""
set_interface_property kd SVD_ADDRESS_GROUP ""

add_interface_port kd kd export Input 16


# 
# connection point pwm_out
# 
add_interface pwm_out conduit end
set_interface_property pwm_out associatedClock clock
set_interface_property pwm_out associatedReset ""
set_interface_property pwm_out ENABLED true
set_interface_property pwm_out EXPORT_OF ""
set_interface_property pwm_out PORT_NAME_MAP ""
set_interface_property pwm_out CMSIS_SVD_VARIABLES ""
set_interface_property pwm_out SVD_ADDRESS_GROUP ""

add_interface_port pwm_out pwm_out export Output 8


# 
# connection point threshold
# 
add_interface threshold conduit end
set_interface_property threshold associatedClock clock
set_interface_property threshold associatedReset ""
set_interface_property threshold ENABLED true
set_interface_property threshold EXPORT_OF ""
set_interface_property threshold PORT_NAME_MAP ""
set_interface_property threshold CMSIS_SVD_VARIABLES ""
set_interface_property threshold SVD_ADDRESS_GROUP ""

add_interface_port threshold threshold export Input 16


# 
# connection point clock_slow
# 
add_interface clock_slow clock end
set_interface_property clock_slow clockRate 0
set_interface_property clock_slow ENABLED true
set_interface_property clock_slow EXPORT_OF ""
set_interface_property clock_slow PORT_NAME_MAP ""
set_interface_property clock_slow CMSIS_SVD_VARIABLES ""
set_interface_property clock_slow SVD_ADDRESS_GROUP ""

add_interface_port clock_slow clk_slow clk Input 1

