# TCL File Generated by Component Editor 20.1
# Tue May 27 02:27:14 BST 2025
# DO NOT MODIFY


# 
# preProcess_block "preProcess_block" v1.0
# Cameron Wade 2025.05.27.02:27:14
# Timing Signal generation
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module preProcess_block
# 
set_module_property DESCRIPTION "Timing Signal generation"
set_module_property NAME preProcess_block
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Cameron Wade"
set_module_property DISPLAY_NAME preProcess_block
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL preprocess_block
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file preProcess_block.v VERILOG PATH 2PreProcess/preProcess_block.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 100000000
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point dir
# 
add_interface dir conduit end
set_interface_property dir associatedClock clock
set_interface_property dir associatedReset ""
set_interface_property dir ENABLED true
set_interface_property dir EXPORT_OF ""
set_interface_property dir PORT_NAME_MAP ""
set_interface_property dir CMSIS_SVD_VARIABLES ""
set_interface_property dir SVD_ADDRESS_GROUP ""

add_interface_port dir dir export Output 1


# 
# connection point lsync
# 
add_interface lsync conduit end
set_interface_property lsync associatedClock clock
set_interface_property lsync associatedReset ""
set_interface_property lsync ENABLED true
set_interface_property lsync EXPORT_OF ""
set_interface_property lsync PORT_NAME_MAP ""
set_interface_property lsync CMSIS_SVD_VARIABLES ""
set_interface_property lsync SVD_ADDRESS_GROUP ""

add_interface_port lsync lsync export Input 1


# 
# connection point rsync
# 
add_interface rsync conduit end
set_interface_property rsync associatedClock clock
set_interface_property rsync associatedReset ""
set_interface_property rsync ENABLED true
set_interface_property rsync EXPORT_OF ""
set_interface_property rsync PORT_NAME_MAP ""
set_interface_property rsync CMSIS_SVD_VARIABLES ""
set_interface_property rsync SVD_ADDRESS_GROUP ""

add_interface_port rsync rsync export Input 1


# 
# connection point sig
# 
add_interface sig conduit end
set_interface_property sig associatedClock clock
set_interface_property sig associatedReset ""
set_interface_property sig ENABLED true
set_interface_property sig EXPORT_OF ""
set_interface_property sig PORT_NAME_MAP ""
set_interface_property sig CMSIS_SVD_VARIABLES ""
set_interface_property sig SVD_ADDRESS_GROUP ""

add_interface_port sig sig export Input 1


# 
# connection point sig_fall_L
# 
add_interface sig_fall_L conduit end
set_interface_property sig_fall_L associatedClock clock
set_interface_property sig_fall_L associatedReset ""
set_interface_property sig_fall_L ENABLED true
set_interface_property sig_fall_L EXPORT_OF ""
set_interface_property sig_fall_L PORT_NAME_MAP ""
set_interface_property sig_fall_L CMSIS_SVD_VARIABLES ""
set_interface_property sig_fall_L SVD_ADDRESS_GROUP ""

add_interface_port sig_fall_L sig_fall_L export Output 1


# 
# connection point sig_fall_R
# 
add_interface sig_fall_R conduit end
set_interface_property sig_fall_R associatedClock clock
set_interface_property sig_fall_R associatedReset ""
set_interface_property sig_fall_R ENABLED true
set_interface_property sig_fall_R EXPORT_OF ""
set_interface_property sig_fall_R PORT_NAME_MAP ""
set_interface_property sig_fall_R CMSIS_SVD_VARIABLES ""
set_interface_property sig_fall_R SVD_ADDRESS_GROUP ""

add_interface_port sig_fall_R sig_fall_R export Output 1


# 
# connection point sig_rise_L
# 
add_interface sig_rise_L conduit end
set_interface_property sig_rise_L associatedClock clock
set_interface_property sig_rise_L associatedReset ""
set_interface_property sig_rise_L ENABLED true
set_interface_property sig_rise_L EXPORT_OF ""
set_interface_property sig_rise_L PORT_NAME_MAP ""
set_interface_property sig_rise_L CMSIS_SVD_VARIABLES ""
set_interface_property sig_rise_L SVD_ADDRESS_GROUP ""

add_interface_port sig_rise_L sig_rise_L export Output 1


# 
# connection point sig_rise_R
# 
add_interface sig_rise_R conduit end
set_interface_property sig_rise_R associatedClock clock
set_interface_property sig_rise_R associatedReset ""
set_interface_property sig_rise_R ENABLED true
set_interface_property sig_rise_R EXPORT_OF ""
set_interface_property sig_rise_R PORT_NAME_MAP ""
set_interface_property sig_rise_R CMSIS_SVD_VARIABLES ""
set_interface_property sig_rise_R SVD_ADDRESS_GROUP ""

add_interface_port sig_rise_R sig_rise_R export Output 1


# 
# connection point sig_time_L
# 
add_interface sig_time_L conduit end
set_interface_property sig_time_L associatedClock clock
set_interface_property sig_time_L associatedReset ""
set_interface_property sig_time_L ENABLED true
set_interface_property sig_time_L EXPORT_OF ""
set_interface_property sig_time_L PORT_NAME_MAP ""
set_interface_property sig_time_L CMSIS_SVD_VARIABLES ""
set_interface_property sig_time_L SVD_ADDRESS_GROUP ""

add_interface_port sig_time_L sig_time_L export Output 32


# 
# connection point split_sync_time
# 
add_interface split_sync_time conduit end
set_interface_property split_sync_time associatedClock clock
set_interface_property split_sync_time associatedReset ""
set_interface_property split_sync_time ENABLED true
set_interface_property split_sync_time EXPORT_OF ""
set_interface_property split_sync_time PORT_NAME_MAP ""
set_interface_property split_sync_time CMSIS_SVD_VARIABLES ""
set_interface_property split_sync_time SVD_ADDRESS_GROUP ""

add_interface_port split_sync_time split_sync_time export Output 32


# 
# connection point sync_start
# 
add_interface sync_start conduit end
set_interface_property sync_start associatedClock clock
set_interface_property sync_start associatedReset ""
set_interface_property sync_start ENABLED true
set_interface_property sync_start EXPORT_OF ""
set_interface_property sync_start PORT_NAME_MAP ""
set_interface_property sync_start CMSIS_SVD_VARIABLES ""
set_interface_property sync_start SVD_ADDRESS_GROUP ""

add_interface_port sync_start sync_start export Output 1


# 
# connection point t_ltr
# 
add_interface t_ltr conduit end
set_interface_property t_ltr associatedClock clock
set_interface_property t_ltr associatedReset ""
set_interface_property t_ltr ENABLED true
set_interface_property t_ltr EXPORT_OF ""
set_interface_property t_ltr PORT_NAME_MAP ""
set_interface_property t_ltr CMSIS_SVD_VARIABLES ""
set_interface_property t_ltr SVD_ADDRESS_GROUP ""

add_interface_port t_ltr t_ltr export Output 32


# 
# connection point t_rtl
# 
add_interface t_rtl conduit end
set_interface_property t_rtl associatedClock clock
set_interface_property t_rtl associatedReset ""
set_interface_property t_rtl ENABLED true
set_interface_property t_rtl EXPORT_OF ""
set_interface_property t_rtl PORT_NAME_MAP ""
set_interface_property t_rtl CMSIS_SVD_VARIABLES ""
set_interface_property t_rtl SVD_ADDRESS_GROUP ""

add_interface_port t_rtl t_rtl export Output 32


# 
# connection point sig_time_R
# 
add_interface sig_time_R conduit end
set_interface_property sig_time_R associatedClock clock
set_interface_property sig_time_R associatedReset ""
set_interface_property sig_time_R ENABLED true
set_interface_property sig_time_R EXPORT_OF ""
set_interface_property sig_time_R PORT_NAME_MAP ""
set_interface_property sig_time_R CMSIS_SVD_VARIABLES ""
set_interface_property sig_time_R SVD_ADDRESS_GROUP ""

add_interface_port sig_time_R sig_time_R export Output 32


# 
# connection point dir_cp
# 
add_interface dir_cp conduit end
set_interface_property dir_cp associatedClock clock
set_interface_property dir_cp associatedReset ""
set_interface_property dir_cp ENABLED true
set_interface_property dir_cp EXPORT_OF ""
set_interface_property dir_cp PORT_NAME_MAP ""
set_interface_property dir_cp CMSIS_SVD_VARIABLES ""
set_interface_property dir_cp SVD_ADDRESS_GROUP ""

add_interface_port dir_cp dir_cp export Output 1

