# TCL File Generated by Component Editor 20.1
# Tue May 27 02:26:46 BST 2025
# DO NOT MODIFY


# 
# output_conversion "output_conversion" v1.0
# Cameron Wade 2025.05.27.02:26:46
# polyphase upsample, mute and volume
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module output_conversion
# 
set_module_property DESCRIPTION "polyphase upsample, mute and volume"
set_module_property NAME output_conversion
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Cameron Wade"
set_module_property DISPLAY_NAME output_conversion
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL output_conversion
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file outputConversion.v VERILOG PATH 5OutputConversion/outputConversion.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 100000000
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point mute
# 
add_interface mute conduit end
set_interface_property mute associatedClock clock
set_interface_property mute associatedReset ""
set_interface_property mute ENABLED true
set_interface_property mute EXPORT_OF ""
set_interface_property mute PORT_NAME_MAP ""
set_interface_property mute CMSIS_SVD_VARIABLES ""
set_interface_property mute SVD_ADDRESS_GROUP ""

add_interface_port mute mute export Input 1


# 
# connection point out_R
# 
add_interface out_R conduit end
set_interface_property out_R associatedClock clock
set_interface_property out_R associatedReset ""
set_interface_property out_R ENABLED true
set_interface_property out_R EXPORT_OF ""
set_interface_property out_R PORT_NAME_MAP ""
set_interface_property out_R CMSIS_SVD_VARIABLES ""
set_interface_property out_R SVD_ADDRESS_GROUP ""

add_interface_port out_R out_R export Output 16


# 
# connection point sample_L
# 
add_interface sample_L conduit end
set_interface_property sample_L associatedClock clock
set_interface_property sample_L associatedReset ""
set_interface_property sample_L ENABLED true
set_interface_property sample_L EXPORT_OF ""
set_interface_property sample_L PORT_NAME_MAP ""
set_interface_property sample_L CMSIS_SVD_VARIABLES ""
set_interface_property sample_L SVD_ADDRESS_GROUP ""

add_interface_port sample_L sample_L export Input 16


# 
# connection point sample_R
# 
add_interface sample_R conduit end
set_interface_property sample_R associatedClock clock
set_interface_property sample_R associatedReset ""
set_interface_property sample_R ENABLED true
set_interface_property sample_R EXPORT_OF ""
set_interface_property sample_R PORT_NAME_MAP ""
set_interface_property sample_R CMSIS_SVD_VARIABLES ""
set_interface_property sample_R SVD_ADDRESS_GROUP ""

add_interface_port sample_R sample_R export Input 16


# 
# connection point valid_L
# 
add_interface valid_L conduit end
set_interface_property valid_L associatedClock clock
set_interface_property valid_L associatedReset ""
set_interface_property valid_L ENABLED true
set_interface_property valid_L EXPORT_OF ""
set_interface_property valid_L PORT_NAME_MAP ""
set_interface_property valid_L CMSIS_SVD_VARIABLES ""
set_interface_property valid_L SVD_ADDRESS_GROUP ""

add_interface_port valid_L valid_L export Input 1


# 
# connection point valid_R
# 
add_interface valid_R conduit end
set_interface_property valid_R associatedClock clock
set_interface_property valid_R associatedReset ""
set_interface_property valid_R ENABLED true
set_interface_property valid_R EXPORT_OF ""
set_interface_property valid_R PORT_NAME_MAP ""
set_interface_property valid_R CMSIS_SVD_VARIABLES ""
set_interface_property valid_R SVD_ADDRESS_GROUP ""

add_interface_port valid_R valid_R export Input 1


# 
# connection point valid_out
# 
add_interface valid_out conduit end
set_interface_property valid_out associatedClock clock
set_interface_property valid_out associatedReset ""
set_interface_property valid_out ENABLED true
set_interface_property valid_out EXPORT_OF ""
set_interface_property valid_out PORT_NAME_MAP ""
set_interface_property valid_out CMSIS_SVD_VARIABLES ""
set_interface_property valid_out SVD_ADDRESS_GROUP ""

add_interface_port valid_out valid_out export Output 1


# 
# connection point volume
# 
add_interface volume conduit end
set_interface_property volume associatedClock clock
set_interface_property volume associatedReset ""
set_interface_property volume ENABLED true
set_interface_property volume EXPORT_OF ""
set_interface_property volume PORT_NAME_MAP ""
set_interface_property volume CMSIS_SVD_VARIABLES ""
set_interface_property volume SVD_ADDRESS_GROUP ""

add_interface_port volume volume export Input 8


# 
# connection point out_L
# 
add_interface out_L conduit end
set_interface_property out_L associatedClock clock
set_interface_property out_L associatedReset ""
set_interface_property out_L ENABLED true
set_interface_property out_L EXPORT_OF ""
set_interface_property out_L PORT_NAME_MAP ""
set_interface_property out_L CMSIS_SVD_VARIABLES ""
set_interface_property out_L SVD_ADDRESS_GROUP ""

add_interface_port out_L out_L export Output 16

