# TCL File Generated by Component Editor 20.1
# Mon May 26 15:40:58 BST 2025
# DO NOT MODIFY


# 
# spi_command_decoder "spi_command_decoder" v1.0
# Cameron Wade 2025.05.26.15:40:58
# takes SPI signal, puts values in registers
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module spi_command_decoder
# 
set_module_property DESCRIPTION "takes SPI signal, puts values in registers"
set_module_property NAME spi_command_decoder
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Cameron Wade"
set_module_property DISPLAY_NAME spi_command_decoder
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL spi_command_decoder
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file spi_command_decoder.v VERILOG PATH 1spi_command_decoder/spi_command_decoder.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 100000000
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point avalon_streaming_sink
# 
add_interface avalon_streaming_sink avalon_streaming end
set_interface_property avalon_streaming_sink associatedClock clock
set_interface_property avalon_streaming_sink associatedReset reset
set_interface_property avalon_streaming_sink dataBitsPerSymbol 8
set_interface_property avalon_streaming_sink errorDescriptor ""
set_interface_property avalon_streaming_sink firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_sink maxChannel 0
set_interface_property avalon_streaming_sink readyLatency 0
set_interface_property avalon_streaming_sink ENABLED true
set_interface_property avalon_streaming_sink EXPORT_OF ""
set_interface_property avalon_streaming_sink PORT_NAME_MAP ""
set_interface_property avalon_streaming_sink CMSIS_SVD_VARIABLES ""
set_interface_property avalon_streaming_sink SVD_ADDRESS_GROUP ""

add_interface_port avalon_streaming_sink stream_data data Input 8
add_interface_port avalon_streaming_sink stream_valid valid Input 1


# 
# connection point ki
# 
add_interface ki conduit end
set_interface_property ki associatedClock clock
set_interface_property ki associatedReset ""
set_interface_property ki ENABLED true
set_interface_property ki EXPORT_OF ""
set_interface_property ki PORT_NAME_MAP ""
set_interface_property ki CMSIS_SVD_VARIABLES ""
set_interface_property ki SVD_ADDRESS_GROUP ""

add_interface_port ki ki export Output 16


# 
# connection point kp
# 
add_interface kp conduit end
set_interface_property kp associatedClock clock
set_interface_property kp associatedReset ""
set_interface_property kp ENABLED true
set_interface_property kp EXPORT_OF ""
set_interface_property kp PORT_NAME_MAP ""
set_interface_property kp CMSIS_SVD_VARIABLES ""
set_interface_property kp SVD_ADDRESS_GROUP ""

add_interface_port kp kp export Output 16


# 
# connection point kd
# 
add_interface kd conduit end
set_interface_property kd associatedClock clock
set_interface_property kd associatedReset ""
set_interface_property kd ENABLED true
set_interface_property kd EXPORT_OF ""
set_interface_property kd PORT_NAME_MAP ""
set_interface_property kd CMSIS_SVD_VARIABLES ""
set_interface_property kd SVD_ADDRESS_GROUP ""

add_interface_port kd kd export Output 16


# 
# connection point mute
# 
add_interface mute conduit end
set_interface_property mute associatedClock clock
set_interface_property mute associatedReset ""
set_interface_property mute ENABLED true
set_interface_property mute EXPORT_OF ""
set_interface_property mute PORT_NAME_MAP ""
set_interface_property mute CMSIS_SVD_VARIABLES ""
set_interface_property mute SVD_ADDRESS_GROUP ""

add_interface_port mute mute export Output 1


# 
# connection point focus_signal
# 
add_interface focus_signal conduit end
set_interface_property focus_signal associatedClock clock
set_interface_property focus_signal associatedReset ""
set_interface_property focus_signal ENABLED true
set_interface_property focus_signal EXPORT_OF ""
set_interface_property focus_signal PORT_NAME_MAP ""
set_interface_property focus_signal CMSIS_SVD_VARIABLES ""
set_interface_property focus_signal SVD_ADDRESS_GROUP ""

add_interface_port focus_signal focus_signal export Output 16


# 
# connection point threshold
# 
add_interface threshold conduit end
set_interface_property threshold associatedClock clock
set_interface_property threshold associatedReset ""
set_interface_property threshold ENABLED true
set_interface_property threshold EXPORT_OF ""
set_interface_property threshold PORT_NAME_MAP ""
set_interface_property threshold CMSIS_SVD_VARIABLES ""
set_interface_property threshold SVD_ADDRESS_GROUP ""

add_interface_port threshold threshold export Output 16


# 
# connection point volume
# 
add_interface volume conduit end
set_interface_property volume associatedClock clock
set_interface_property volume associatedReset ""
set_interface_property volume ENABLED true
set_interface_property volume EXPORT_OF ""
set_interface_property volume PORT_NAME_MAP ""
set_interface_property volume CMSIS_SVD_VARIABLES ""
set_interface_property volume SVD_ADDRESS_GROUP ""

add_interface_port volume volume export Output 8

